"""add is_favorite and display_order

Revision ID: 62c8738dcee0
Revises: 7f79a897df6a
Create Date: 2026-03-04 18:13:21.639470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62c8738dcee0'
down_revision: Union[str, None] = '7f79a897df6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredients', 'quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.add_column('refrigerator_members', sa.Column('is_favorite', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('refrigerator_members', sa.Column('display_order', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('storage_boxes', sa.Column('display_order', sa.Integer(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storage_boxes', 'display_order')
    op.drop_column('refrigerator_members', 'display_order')
    op.drop_column('refrigerator_members', 'is_favorite')
    op.alter_column('ingredients', 'quantity',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
