"""initial_tables

Revision ID: 7f79a897df6a
Revises: 
Create Date: 2026-03-03 19:36:09.721593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f79a897df6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refrigerators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('oauth_provider', sa.String(length=20), nullable=False),
    sa.Column('oauth_id', sa.String(length=100), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oauth_provider', 'oauth_id', name='uq_user_oauth')
    )
    op.create_table('refrigerator_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('refrigerator_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'GUEST', name='memberrole'), nullable=False),
    sa.ForeignKeyConstraint(['refrigerator_id'], ['refrigerators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refrigerator_id', 'user_id', name='uq_fridge_user')
    )
    op.create_index('ix_refrigerator_members_user_id', 'refrigerator_members', ['user_id'], unique=False)
    op.create_table('storage_boxes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('refrigerator_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('ROOM', 'FRIDGE', 'FREEZER', name='storagetype'), nullable=False),
    sa.ForeignKeyConstraint(['refrigerator_id'], ['refrigerators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_storage_boxes_refrigerator_id', 'storage_boxes', ['refrigerator_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cooking_skill', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='cookingskill'), nullable=True),
    sa.Column('max_time', sa.Integer(), nullable=True),
    sa.Column('allergies', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('cooking_tools', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('dietary_habits', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('storage_box_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False, server_default='개'),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['storage_box_id'], ['storage_boxes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingredients_expiry_date', 'ingredients', ['expiry_date'], unique=False)
    op.create_index('ix_ingredients_name', 'ingredients', ['name'], unique=False)
    op.create_index('ix_ingredients_storage_box_id', 'ingredients', ['storage_box_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ingredients_storage_box_id', table_name='ingredients')
    op.drop_index('ix_ingredients_name', table_name='ingredients')
    op.drop_index('ix_ingredients_expiry_date', table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_table('user_preferences')
    op.drop_index('ix_storage_boxes_refrigerator_id', table_name='storage_boxes')
    op.drop_table('storage_boxes')
    op.drop_index('ix_refrigerator_members_user_id', table_name='refrigerator_members')
    op.drop_table('refrigerator_members')
    op.drop_table('users')
    op.drop_table('refrigerators')
    # ### end Alembic commands ###
